
export const DOCUMENTATION  = [
    {
       title:'HTML5',
       url:'https://developer.mozilla.org/en-US/docs/Glossary/HTML5',
       favorite:false
    },
    {
        title:'CSS3',
        url:'https://css-tricks.com/',
        favorite:false
     },
     {
        title:'JS',
        url:'https://lenguajejs.com/javascript/introduccion/ecmascript/',
        favorite:false,  
     },
     {
        title:'TS',
        url:'https://www.typescriptlang.org/',
        favorite:false  
     },
     {
        title:'Angular',
        url:'https://angular.io/',
        favorite:false
     },
     {
        title:'Node',
        url:'https://nodejs.org/es',
        favorite:false
     },
     {
      title:'Express',
      url:'https://expressjs.com/',
      favorite:false
   },
   {
      title:'MySQL',
      url:'https://dev.mysql.com/',
      favorite:false
   },
   {
      title:'Firebase',
      url:'https://firebase.google.com/?gad=1&gclid=CjwKCAjwvrOpBhBdEiwAR58-3JEWcA7jpg5B9I6fyHKM6B1bJqgEsKseYYr_E34C3NqOQAfUf3UkThoCqm4QAvD_BwE&gclsrc=aw.ds&hl=es-419',
      favorite:false
   },
   {
      title:'React',
      url:'https://es.react.dev/',
      favorite:false
   },
   {
      title:'Bootstrap',
      url:'https://getbootstrap.com/',
      favorite:false
   },
   {
      title:'Frontend Mentor',
      url:'https://www.frontendmentor.io/challenges',
      favorite:false
   },
   {
      title:'Documentos Web MDN',
      url:'https://developer.mozilla.org/es/',
      favorite:false
   },
   {
      title:'Google Fonts',
      url:'https://fonts.google.com/',
      favorite:false
   },
   {
      title:' API REST Countries',
      url:'https://restcountries.com/#api-endpoints-v3-all',
      favorite:false
   },
   {
      title:'Flaticon',
      url:'https://www.flaticon.es/',
      favorite:false
   },
   {
      title:'API OMDb Open Movie Database',
      url:'https://www.omdbapi.com/', 
      favorite:false
   },
   {
      title:'Stack Overflow',
      url:'https://stackoverflow.com/',
      favorite:false
   },
   {
      title:'Replit',
      url:'https://replit.com/',
      favorite:false
   },
   {
      title:'Chat GPT',
      url:'https://chat.openai.com/',
      favorite:false
   },
   {
      title:'uiGradientes',
      url:'https://uigradients.com/#Petrol',
      favorite:false
   },
   {
      title:'bootswatch',
      url:'https://cdnjs.com/libraries/bootswatch',
      favorite:false
   },
   {
      title:'API News',
      url:'https://newsapi.org/',
      favorite:false
   },
   {
      title:'Spinkit',
      url:'https://tobiasahlin.com/spinkit/',
      favorite:false
   },
   {
      title:'Github',
      url:'https://github.com/',
      favorite:false
   },
   {
      title:'Spinkit',
      url:'https://tobiasahlin.com/spinkit/',
      favorite:false
   },
   {
      title:'Linkedin',
      url:'https://www.linkedin.com/',
      favorite:false
   },
   {
      title:'Microsoft Official Exam Preparation',
      url:'https://az204webapp2023.azurewebsites.net/',
      favorite:false
   },
   {
      title:'Codédex',
      url:'https://www.codedex.io/',
      favorite:false
   },
   {
      title:'Hirelene',
      url:'https://hireline.io/mx',
      favorite:false
   },
   {
      title:'Patrones de Diseño',
      url:'https://refactoring.guru/es/design-patterns',
      favorite:false
   },
   {
      title:'Typedoc',
      url:'https://typedoc.org/#quick-start',
      favorite:false
   },
   {
      title:'Fullstack Open',
      url:'https://fullstackopen.com/es/',
      favorite:false
   },
   {
      title:'Reqres',
      url:'https://reqres.in/',
      favorite:false
   },
   {
      title:'StackBlitz',
      url:'https://stackblitz.com/',
      favorite:false
   },
   {
      title:'Angular Material',
      url:'https://material.angular.io/',
      favorite:false
   },
   {
      title:'Random User',
      url:'https://randomuser.me/',
      favorite:false
   },
   {
      title:'Canva',
      url:'https://www.canva.com/',
      favorite:false
   },
   {
      title:'Netlify',
      url:'https://app.netlify.com/signup/start',
      favorite:false
   },
   {
      title:'Section Separator Generator',
      url:'https://wweb.dev/resources/css-separator-generator',
      favorite:false
   },
   {
      title:'CSS Matic',
      url:'https://www.cssmatic.com/box-shadow',
      favorite:false
   },
   {
      title:'Anime JS',
      url:'https://animejs.com/',
      favorite:false
   },
   {
      title:'Animate on Scroll Library',
      url:'https://michalsnik.github.io/aos/',
      favorite:false
   },
   {
      title:'Kinsta',
      url:'https://kinsta.com/es/blog/principales-tendencias-de-diseno-web/#more-effects-and-animations',
      favorite:false
   },
   {
      title:'SVG Backgrounds',
      url:'https://www.svgbackgrounds.com/',
      favorite:false
   },
   {
      title:'Conversor nekoCalc',
      url:'https://nekocalc.com/es/px-a-em-conversor',
      favorite:false
   },
   {
      title:'Color neko color',
      url:'https://nekocolor.com',
      favorite:false
   },
   {
      title:'Flexbox',
      url:'https://css-tricks.com/snippets/css/a-guide-to-flexbox/',
      favorite:false
   },
   {
      title:'Curated Colors in context',
      url:'https://www.happyhues.co/',
      favorite:false
   },
   {
      title:'Webflow',
      url:'https://webflow.com/',
      favorite:false
   },
   {
      title:'API Rick and Morty',
      url:'https://rickandmortyapi.com/',
      favorite:false
   },
   {
      title:'Am I responsive?',
      url:'https://ui.dev/amiresponsive',
      favorite:false
   },
   {
      title:'Figma',
      url:'https://www.figma.com/',
      favorite:false
   },
   {
      title:'Excalidraw',
      url:'https://excalidraw.com/',
      favorite:false
   },
   {
      title:'Coolors',
      url:'https://coolors.co/',
      favorite:false
   },
   {
      title:'Vercel',
      url:'https://vercel.com/dashboard',
      favorite:false
   },
   {
      title:'Worbench',
      url:'https://dev.mysql.com/downloads/workbench/',
      favorite:false
   },
   {
      title:'Visula Studio Code',
      url:'https://code.visualstudio.com/',
      favorite:false
   },
   {
      title:'XAMPP',
      url:'https://www.apachefriends.org/es/index.html',
      favorite:false
   },
   {
      title:'Postman',
      url:'https://www.postman.com/',
      favorite:false
   },
   {
      title:'W3Schools',
      url:'https://www.w3schools.com/',
      favorite:false
   },
]